### ISSUE TITLE
use spread operator for props shorthand

### ISSUE THREAD

**Issue by Yarin-C** [stasrdv/React-Portfolio#8]
https://github.com/stasrdv/React-Portfolio/blob/6d3440e699cdc15cd783f1cbf924d66b6a8d7c21/src/components/portfoliob-board.js#L45

you can use the spread operator to assign same name shorthand props, like so:

```
<Card { ... { key: singleCard.id, ...singleCard } } />
```

this will break down all the props in singleCard, and because the singleCard props are the same name as the ```<Card />``` props, they will be matched. please notice that key is still required to be matched manually, as singleCard does not have a key prop, but an id one

**Comment by stasrdv** [comment]
issue
